# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 03:42
from __future__ import unicode_literals

import colorful.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_create_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(1)])),
                ('name', models.TextField()),
                ('primary_colour', colorful.fields.RGBColorField()),
                ('secondary_colour', colorful.fields.RGBColorField(blank=True, null=True)),
                ('tertiary_colour', colorful.fields.RGBColorField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='league',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.League'),
        ),
    ]
