# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 05:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_create_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.RegexValidator('^\\w+$')])),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='league',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.RegexValidator('^\\w+$')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.RegexValidator('^\\w+$')]),
        ),
        migrations.AddField(
            model_name='season',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.League'),
        ),
    ]
