# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 10:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_create_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.RegexValidator('^\\w+$')])),
                ('name', models.TextField()),
            ],
        ),
    ]
