# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_create_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('team_1_goals', models.PositiveIntegerField(default=0)),
                ('team_1_behinds', models.PositiveIntegerField(default=0)),
                ('team_2_goals', models.PositiveIntegerField(default=0)),
                ('team_2_behinds', models.PositiveIntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Season')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='models.Team')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='models.Team')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='models.Venue')),
            ],
        ),
    ]
