# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-14 05:39
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_create_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='primary_colour',
            field=colorful.fields.RGBColorField(blank=True, null=True),
        ),
    ]
