# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-23 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_team_colours_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueAlternativeName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Venue')),
            ],
        ),
    ]
