# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-23 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_create_venue_alternative_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuealternativename',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_names', to='models.Venue'),
        ),
    ]
