# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-23 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_delete_venue_alternative_names'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('start', 'season', 'team_1', 'team_2')]),
        ),
    ]
