# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_add_latitude_and_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAlternativeName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_names', to='models.Team')),
            ],
        ),
    ]
