language: python
python:
    - "3.5"
    - "3.5-dev"
    - "nightly"
services:
    - postgresql
env:
    - POSTGRES_DB="openfootydata" POSTGRES_USER="postgres" POSTGRES_PASSWORD="" POSTGRES_HOST="127.0.0.1"
before_script:
    - psql -c 'CREATE DATABASE openfootydata;' -U postgres
install:
    - pip install -r requirements.txt
script:
    - python manage.py test
after_success:
    - bash <(curl -s https://codecov.io/bash)
    - pip install codeclimate-test-reporter && codeclimate-test-reporter
